-- 코드를 입력하세요
# SELECT DATE_FORMAT(N.SALES_DATE, '%Y-%d-%m') AS SALES_DATE, N.PRODUCT_ID, COALESCE(N.USER_ID, 'NULL') AS USER_ID, N.SALES_AMOUNT
#     FROM ONLINE_SALE AS N
#     JOIN OFFLINE_SALE AS F ON N.PRODUCT_ID = F.PRODUCT_ID
#     WHERE N.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
#     ORDER BY N.SALES_DATE, N.PRODUCT_ID, N.USER_ID;
    
# SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
#     FROM ONLINE_SALE
#     WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31';
# UNION ALL
# SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
#     FROM OFFLINE_SALE
#     WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31';

(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%')
    
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;