-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
        ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE   # 평균 리뷰점수
    FROM REST_INFO AS I
    JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID 
    WHERE LEFT(I.ADDRESS, 2) = '서울'   # 서울에 위치한
    GROUP BY I.REST_ID   # 가게 별 그룹핑
    ORDER BY SCORE DESC, FAVORITES DESC;