-- 코드를 입력하세요

# MAX 날짜를 살펴봐야하는 이유(=가장 최근 대여기록 기준으로 사용해야하는 이유)
SELECT *, MAX(START_DATE), MAX(END_DATE)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID;

SELECT CAR_ID,
        MAX(IF('2022-10-16' BETWEEN START_DATE AND END_DATE, '대여중', '대여 가능')) AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC;