-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT AS P
    JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY P.PRODUCT_NAME
    ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID;