-- 코드를 입력하세요

SELECT a.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR AS a
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b ON a.CAR_ID = b.CAR_ID
    WHERE MONTH(START_DATE) = 10
        AND CAR_TYPE = '세단'
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC;